name: binder-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - git+https://github.com/morphomatics/morphomatics.git@cad8f28c708a5165355fdc93830ac7a328de41a9#egg=morphomatics
